### ISSUE TITLE
Make this show up as a fork of chroagh.

### ISSUE THREAD

**Issue by GetzMikalsen** [qntmpkts/chroagh-nonfork#4]
This project didnt show up as a fork of chroagh, I am very thankful of your work but it was incredibly hard to find it.

**Comment by zhaofengli** [comment]
To make it easier to keep up with upstream, I rebased all changes on this repo (except stuff no longer supported by upstream crouton) against crouton at [zhaofengli/crouton](https://github.com/zhaofengli/crouton).

I hope @qntmpkts can do this so we can eventually merge Arch support into crouton.

**Comment by qntmpkts** [comment]
I'd rather not do this given the tracked issues I have here, so if anyone knows of reliable method, that would be helpful.

**Comment by qntmpkts** [comment]
This has been done. See qntmpkts/chroagh.
